workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - thelab-arm64

stages:
  - test
  - release

services: []

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.9.0

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  services:
    - name: postgres:18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
      alias: db
  script:
    - uv sync --all-extras
    - uv run tox
  parallel:
    matrix:
      - IMAGE: "3.11"
        TOX_SKIP_ENV: "^(?!py311-)"
      - IMAGE: "3.12"
        TOX_SKIP_ENV: "^(?!py312-)"
      - IMAGE: "3.13"
        TOX_SKIP_ENV: "^(?!py313-)"
      - IMAGE: "3.14"
        TOX_SKIP_ENV: "^(?!py314-)"
