# Generated by Django 2.1.4 on 2019-01-07 16:22

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("shopify_sync", "0001_initial"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="product",
            name="body_html",
            field=models.TextField(default=""),
        ),
    ]
