# Generated by Django 2.1.5 on 2019-01-07 18:18

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("shopify_sync", "0002_auto_20190107_1622"),
        ("shopify_sync", "0002_auto_20181220_1714"),
    ]

    operations: ClassVar = []
