# Generated by Django 2.2.2 on 2019-06-21 08:52

from typing import ClassVar

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("shopify_sync", "0003_merge_20190107_1818"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopify_sync.Customer",
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopify_sync.Customer",
            ),
        ),
    ]
