# Generated by Django 2.2.2 on 2019-07-12 07:02

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("shopify_sync", "0005_remove_customer_default_address"),
    ]

    operations: ClassVar = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
