# Generated by Django 2.2.5 on 2019-09-05 12:18

from typing import ClassVar

from django.db import migrations
import jsonfield.fields

import shopify_sync.encoders


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("shopify_sync", "0007_order_shipping_address"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="order",
            name="fulfillments",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list, null=True
            ),
        ),
    ]
