# Generated by Django 3.2.16 on 2023-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0009_auto_20190918_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_token",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.CharField(max_length=64),
        ),
    ]
