# Generated by Django 3.0.8 on 2024-08-06 14:05

from django.db import migrations, models
import jsonfield.fields

import shopify_sync.encoders


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0010_auto_20230222_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customcollection",
            name="image",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="properties",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="tax_lines",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client_details",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_codes",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fulfillments",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="note_attributes",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_lines",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_lines",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="county_taxes",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="eligible_for_payments",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="google_apps_login_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="password_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="public",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="requires_extra_payments_agreement",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="tax_shipping",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="taxes_included",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="smartcollection",
            name="image",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="smartcollection",
            name="rules",
            field=jsonfield.fields.JSONField(
                default=shopify_sync.encoders.empty_list,
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="fields",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="metafield_namespaces",
            field=jsonfield.fields.JSONField(
                dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                null=True,
            ),
        ),
    ]
