# Generated by Django 6.0.3 on 2026-03-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopify_sync", "0011_auto_20240806_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="orders_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_spent",
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
    ]
