# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopify_sync", "0012_alter_customer_orders_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="processing_method",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="source_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="fulfillment_service",
            field=models.CharField(max_length=255),
        ),
    ]
